format = """
[](pine)$os[](fg:pine bg:forest)$shell[](fg:forest bg:moss)$hostname[](fg:moss bg:rose)$username$directory[](fg:rose bg:orange)$git_branch$git_status[](fg:orange bg:blue)$cmd_duration[](fg:blue bg:slate)$time[](fg:slate)
$character
"""

add_newline = true
command_timeout = 1000
palette = "terminalninja"

[palettes.terminalninja]
teal = "#003543"
pine = "#0c2417"
forest = "#153622"
moss = "#1d4a2e"
fern = "#27603b"
mint = "#00c983"
rose = "#a00634"
orange = "#c5400b"
slate = "#4c3196"
blue = "#0e4e80"
cyan = "#45F1C2"
red = "#ff4d4d"
white = "#ffffff"

[os]
disabled = false
style = "bg:pine fg:mint"
format = "[ $symbol ]($style)"

[shell]
disabled = false
style = "bg:forest fg:white"
format = "[ $indicator ]($style)"
bash_indicator = "bash"
cmd_indicator = "cmd"
fish_indicator = "fish"
ion_indicator = "ion"
nu_indicator = "nushell"
powershell_indicator = "PowerShell"
tcsh_indicator = "tcsh"
xonsh_indicator = "xonsh"
zsh_indicator = "zsh"
unknown_indicator = "shell"

[os.symbols]
Alpine = "\uE70F"
Amazon = "\uE70F"
Android = "\uE70F"
Arch = "\uE70F"
Artix = "\uE70F"
CentOS = "\uE70F"
Debian = "\uE70F"
DragonFly = "DragonFly"
Emscripten = "Emscripten"
EndeavourOS = "\uE70F"
Fedora = "\uE70F"
FreeBSD = "FreeBSD"
Garuda = "\uE70F"
Gentoo = "\uE70F"
HardenedBSD = "HardenedBSD"
Illumos = "Illumos"
Linux = "\uE70F"
Mabox = "\uE70F"
Macos = "\uE711"
Manjaro = "\uE70F"
Mariner = "\uE70F"
MidnightBSD = "MidnightBSD"
Mint = "\uE70F"
NetBSD = "NetBSD"
NixOS = "\uE70F"
OpenBSD = "OpenBSD"
openSUSE = "\uE70F"
OracleLinux = "\uE70F"
Pop = "\uE70F"
Raspbian = "\uE70F"
Redhat = "\uE70F"
RedHatEnterprise = "\uE70F"
RockyLinux = "\uE70F"
Redox = "Redox"
Solus = "\uE70F"
SUSE = "\uE70F"
Ubuntu = "\uE70F"
Unknown = "Unknown"
Void = "\uE70F"
Windows = "\uE70F"

[hostname]
ssh_only = false
style = "bg:moss fg:mint"
format = "[$hostname ]($style)"

[username]
show_always = true
style_user = "fg:white bg:rose"
style_root = "fg:white bg:red"
format = "[$user]($style)"

[directory]
style = "fg:white bg:rose"
read_only = " 󰌾"
format = "[ 󰉋 $path$read_only ]($style)"
truncation_length = 4
truncation_symbol = "…/"
home_symbol = "~"

[git_branch]
symbol = ""
style = "fg:white bg:orange"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:white bg:orange"
format = "[($all_status$ahead_behind )]($style)"

[cmd_duration]
min_time = 500
style = "fg:white bg:blue"
format = "[ 󱎫 $duration ]($style)"

[time]
disabled = false
time_format = "%I:%M %p"
style = "fg:white bg:slate"
format = "[  $time ]($style)"

[character]
success_symbol = "[⚡❯❯](#45F1C2)"
error_symbol = "[⚡❯❯](#ff4d4d)"
vimcmd_symbol = "[❮❮](#45F1C2)"
